{% set name = "djantic" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djantic-{{ version }}.tar.gz
  sha256: 1b074b595879145582a726d9e6491b9c72e53e98efdfd445420c6b12ddfe5a85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=1.8.2
    - django >3.0,<4.0

test:
  imports:
    - djantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jordaneremieff/djantic/
  summary: Pydantic model support for Django ORM
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
